# Generated by Django 6.1 on 2026-09-30 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_task_completion_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description, e.g. "Initial Payment", "Milestone 1".', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional longer description for the client.')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount due in NPR.', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Optional deadline for this payment.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client who is expected to pay.', limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Manager who created this payment request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project this payment request belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='projects.project')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'ordering': ['created_at'],
            },
        ),
    ]
