# Generated by Django 6.1 on 2026-09-30 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_add_payment_request_model'),
        ('projects', '0006_task_completion_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in NPR — always copied server-side from the PaymentRequest.', max_digits=12)),
                ('payment_method', models.CharField(choices=[('SIMULATION', 'Simulation (Dev/Test)'), ('KHALTI', 'Khalti'), ('ESEWA', 'eSewa'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='SIMULATION', help_text='Payment method used for this transaction.', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, default='', help_text='Gateway-assigned transaction/reference ID. Empty for SIMULATION; populated by real gateway in Phase 4+.', max_length=255)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='INITIATED', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Internal: reason for FAILED status. Never exposed to clients.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Timestamp when the transaction was confirmed successful.', null=True)),
                ('client', models.ForeignKey(help_text='Denormalised from payment_request.client.', limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(help_text='The PaymentRequest this transaction is for.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.paymentrequest')),
                ('project', models.ForeignKey(help_text='Denormalised from payment_request.project.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='projects.project')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='payments_pa_client__f88ea3_idx'), models.Index(fields=['payment_request', 'status'], name='payments_pa_payment_56be0a_idx')],
            },
        ),
    ]
