# Generated by Django 6.1 on 2026-09-07 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PROJECT_CREATED', 'Project Created'), ('STAFF_ASSIGNED', 'Staff Assigned'), ('STAFF_REMOVED', 'Staff Removed'), ('TASK_ADDED', 'Task Added'), ('TASK_UPDATED', 'Task Updated'), ('TASK_STATUS', 'Task Status Changed'), ('TASK_DELETED', 'Task Deleted')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Activity',
                'verbose_name_plural': 'Project Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
