# Generated by Django 6.1 on 2026-09-22 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='Staff-reported percentage of completion (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
