# Generated by Django 6.1 on 2026-09-16 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_display_name_user_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rivera Studio', max_length=200, verbose_name='Studio / Workspace name')),
                ('role', models.CharField(default='Freelance Designer & Developer', max_length=150, verbose_name='Your role')),
                ('currency', models.CharField(choices=[('NPR', 'NPR - Nepalese Rupee'), ('USD', '$ USD'), ('EUR', '€ EUR'), ('INR', '₹ INR — Indian Rupee')], default='NPR', max_length=10, verbose_name='Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='accounts.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace Setting',
                'verbose_name_plural': 'Workspace Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
