# Generated by Django 6.1 on 2026-09-03 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_user_display_name_user_profile_picture'),
        ('projects', '0003_project_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('Email_address', models.EmailField(max_length=254)),
                ('phone_number', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Tester', 'Tester'), ('Manager', 'Manager')], max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Working', 'Working'), ('Leave', 'Leave')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='projects.project')),
            ],
        ),
    ]
