# Generated by Django 6.1 on 2026-09-09 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='project',
        ),
    ]
