# Generated by Django 6.1 on 2026-09-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_display_name_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(choices=[('NPR', 'NPR — Nepalese Rupee'), ('USD', 'USD — US Dollar'), ('EUR', 'EUR — Euro'), ('INR', 'INR — Indian Rupee')], default='NPR', help_text='Currency used for all monetary amounts in this workspace.', max_length=3),
        ),
    ]
