# Generated by Django 6.1 on 2026-09-11 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_received', 'Payment received'), ('deadline_reminder', 'Deadline reminder'), ('overdue_alert', 'Overdue alert'), ('client_portal_viewed', 'Client portal viewed'), ('team_member_joined', 'Team member joined'), ('weekly_summary', 'Weekly summary'), ('task_assigned', 'Task assigned'), ('project_assigned', 'Project assigned'), ('general', 'General')], db_index=True, default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_received', models.BooleanField(default=True)),
                ('deadline_reminder', models.BooleanField(default=True)),
                ('overdue_alert', models.BooleanField(default=True)),
                ('client_portal_viewed', models.BooleanField(default=True)),
                ('team_member_joined', models.BooleanField(default=True)),
                ('weekly_summary', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
