# Generated by Django 6.1 on 2026-09-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='account_activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_received', 'Payment received'), ('deadline_reminder', 'Deadline reminder'), ('overdue_alert', 'Overdue alert'), ('client_portal_viewed', 'Client portal viewed'), ('team_member_joined', 'Team member joined'), ('weekly_summary', 'Weekly summary'), ('account_activity', 'Account activity'), ('task_assigned', 'Task assigned'), ('project_assigned', 'Project assigned'), ('general', 'General')], db_index=True, default='general', max_length=50),
        ),
    ]
